config/routes.rb
Rails.application.routes.draw do
  root to: 'authors#index'

  resources :publishers
  resources :books
  resources :authors

  get 'search' => 'books#search'

  namespace :api do
    namespace :v1, defaults: {format: :json} do

      resources :books do
        collection do
          # get 'search' => 'books#search'
        end
      end
    end
  end
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id               :bigint           not null, primary key
#  title            :string
#  isbn             :string
#  price            :string
#  year_publication :string
#  image_url        :string
#  edition          :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  publisher_id     :bigint           not null
#
class Book < ApplicationRecord
  has_many :book_authors
  belongs_to :publisher

  validates :title, presence: true, length: {minimum: 2}
  validates :price, presence: true, allow_blank: false
  validates :year_publication, presence: true, allow_blank: false
  validates :image_url, presence: true, allow_blank: false
  validates :edition, presence: true, numericality: { only_integer: true}
  validate :valid_isbn

  def valid_isbn
    result = []
    isbn = self.isbn
    isbn13  = isbn
    result << (isbn.count("/[^0-9]/i") < 9 ? false : true)
    sum = 0
    isbn = isbn.gsub(/[^0-9a-z ]/i, '').split("")
    isbn.each_with_index do |num, i|
      if i < isbn.length - 1
        digit = num.to_i
        if 0 > digit || 9 < digit
          result << false
        else
          sum += (digit * (10-i))
        end
      end
    end

    last = isbn.last
    result << ((last&.downcase != 'x' && (last.to_i < 0 || last.to_i > 9)) ? false : true)
    sum += ((last&.downcase == 'x') ? 10 : last.to_i)
    # p result.all? && sum % 11 == 0

    if !(result.all? && sum % 11 == 0)
      # try to check for isbn 13
      if ISBN.valid?(isbn13)
        true
      else
        errors.add(:isbn, "Please provide correct ISBN")
      end
    end
  end

end

app/controllers/api/v1/books_controller.rb
include BooksHelper

class Api::V1::BooksController < Api::V1::ApiController

  before_action :check_isbn, :set_book, only: %i[ show ]

  def index
    @books = Book.all
    render json: @books, status: 200
  end

  def show
    render json: @book, status: 200
  end

  private

  def check_isbn
    @isbn = (params[:id]).scan(/[\da-z\s]/i).join
    if !(ISBN.valid?(@isbn))
      render json: { errors: "INVALID ISBN" }, status: 400
    end
  end

  def set_book
    # try to find either 10 or 13 or convert vice-versa
    isbn13 = isbn10_13(@isbn)
    isbn10 = isbn13_10(@isbn)
    @book = Book.where(isbn: [isbn10,isbn13,@isbn]).first

    if @book
      @book
    else
      render json: { errors: "BOOK NOT EXIST" }, status: 404
    end
  end

end

app/controllers/books_controller.rb
include BooksHelper

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = Book.all
  end

  def search
    @errors = []
    @isbn = (params[:isbn])&.scan(/[\da-z\s]/i)&.join

    if !(ISBN.valid?(@isbn))
      @errors << "Please provide correct ISBN"
    else
      isbn13 = isbn10_13(@isbn)
      isbn10 = isbn13_10(@isbn)
      @book = Book.where(isbn: [isbn10,isbn13,@isbn])&.first
      if @book
        @authors = (Author.where(id: @book.book_authors.pluck(:author_id)).complete_name).join(", ")
      else
        @errors << "Book not found"
      end
    end

  end

  def show; end

  def new
    @book = Book.new
    @publishers = Publisher.pluck(:name, :id)
    @authors = Author.all
  end

  def edit; end

  def create
    @book = Book.new(book_params)
    @book.isbn = (params[:book][:isbn]).scan(/[\da-z\s]/i).join
    @publishers = Publisher.pluck(:name, :id)
    @authors = Author.all

    respond_to do |format|
      if @book.save
        author_ids = (params[:book_authors][:author_id]).compact
        author_ids.each do |author_id|
          @book.book_authors.create(author_id: author_id)
        end

        format.html { redirect_to books_url, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :publisher_id, :price, :year_publication, :image_url, :edition)
  end
end

app/helpers/books_helper.rb
module BooksHelper

  def isbn10_13(isbn)
    isbn = (isbn).gsub(/[^0-9a-z ]/i, '')
    proceed = isbn.length == 10 ? true : false
    if proceed
      len = isbn.length

      isbn = "978#{isbn.chop!}".split("")
      result = isbn.join("")
      sum = 0

      three_one = [1, 3].cycle(6)
      isbn.each do |v|
        sum += v.to_i * (three_one.next)
      end
      sub_number = 10 - (sum % 10)
      result = "#{result}#{sub_number}"
      if result.length == 13
        result
      else
        "INVALID ISBN"
      end
    else
      "INVALID ISBN"
    end
  end

  def isbn13_10(isbn)
    isbn = isbn.gsub(/[^0-9a-z ]/i, '')
    nine_78 = isbn.slice(0..2) == "978"
    len = isbn.length
    isbn = isbn.slice!(3..11).split("").map(&:to_i)
    proceed = len == 13 ? true : false
    if proceed && nine_78
      sum = isbn.map.with_index{|x,i| (10-i)*x }.sum
      last_num=0
      while true do
        break if (sum+last_num) % 11 == 0
        last_num += 1
      end

      result = "#{isbn.join("")}#{last_num}"

      if result.length > 10
        if (result.slice(-2..-1).to_i == 10)
          "#{result.slice(0..8)}X"
        else
          "INVALID ISBN"
        end
      else
        result
      end
    else
      "INVALID ISBN"
    end
  end


end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>
  <div class="field">
    <%= form.label :publisher %>
    <%= form.select :publisher_id, @publishers %>
  </div>
  <div class="field">
    <%= form.label :author %>
    <%= collection_select "book_authors", "author_id", @authors, :id, :complete_names, { selected: [1]}, { multiple: true, class: "form-control" } %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div class="field">
    <%= form.label :year_publication %>
    <%= form.text_field :year_publication %>
  </div>
  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>
  <div class="field">
    <%= form.label :edition %>
    <%= form.text_field :edition %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Isbn</th>
      <th>Price</th>
      <th>Year publication</th>
      <th>Image url</th>
      <th>Edition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.isbn %></td>
        <td><%= book.price %></td>
        <td><%= book.year_publication %></td>
        <td><%= book.image_url %></td>
        <td><%= book.edition %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<%= form_tag(search_path, {:method => :get}) do %>
  <div class="field">
    ISBN: <input type="text" class="form-control" id="isbn" name="isbn" value="<%=params[:isbn]%>">
    <button type="submit" class="btn btn-primary">Search</button>
  </div>

<% end %>


<% if @errors.any? %>
  <ul>
    <% @errors.each do |e| %>
      <li> <%=e %> </li>
    <% end %>
  </ul>
<% end %>

<% if @errors.empty? %>
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= @book.isbn %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= @book.publisher.name %>
  </p>

  <p>
    <strong>Authors:</strong>
    <%= @authors %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @book.price %>
  </p>

  <p>
    <strong>Year publication:</strong>
    <%= @book.year_publication %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= @book.image_url %>
  </p>

  <p>
    <strong>Edition:</strong>
    <%= @book.edition %>
  </p>

<% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Year publication:</strong>
  <%= @book.year_publication %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @book.edition %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>